### ISSUE TITLE
lsp version is outdated, "Error (use-package): lsp-mode/:config: Cannot open load file: lsp-clients"

### ISSUE THREAD

**Issue by stradicat** [syl20bnr/spacelpa#2]
`lsp` in spacelpa seems to be outdated; I keep getting messages such as `Error (use-package): lsp-mode/:config: Cannot open load file: lsp-clients`, and such; `spacelpa`'s `lsp` version doesn't work well with `ccls`, `java-mode` and `dap-mode`.

Going back to upstream packages in _Spacemacs_ (to use the current `lsp` version) results in an unstable configuration (`error "Lisp nesting exceeds ‘max-lisp-eval-depth’"`, and many functional impairments).

Setting `spacelpa` back to `nil` makes `lsp` work out of the box with pretty much any language.

[`lsp` version 6 was released in January 2019 after an important rewrite, and many `spacelpa` packages are from late 2018.](https://www.reddit.com/r/emacs/comments/ahzrg0/announcement_lspmode_60_released/)

So, the best of both world would be the current `spacelpa` repo + the latest, "stable" `lsp` version 6.0+, plus its dependencies (`lsp-ui`, `company-lsp`, and dependent packages such as `dap-mode`, `lsp-java`, `lsp-dart`, `ccls`, etc.).

**Comment by tombrk** [comment]
The above is correct. I am experiencing the same problems, which makes Spacelpa unusable after all. Please fix, thanks a lot!

**Comment by syl20bnr** [comment]
Hi, thank you for the PR. The spacelpa repository is a being actively developed again and I updated all the package recently.
See issue: syl20bnr/spacemacs#12652

Not that this is in beta and the feature is not stable, a refactoring of it will be merged soon.

**Comment by iddm** [comment]
I am now having the same problem, with and without using `spacelpa`. The latest emacs on archlinux, the latest `develop` branch, all of the packages were updated. Is there anything else I should try?

**Comment by cody-vibe** [comment]
@vityafx might be related to this change then https://github.com/syl20bnr/spacemacs/pull/13860

Probably should open an issue in Spacemacs together with a full stacktrace of the error

**Comment by iddm** [comment]
> @vityafx might be related to this change then [syl20bnr/spacemacs#13860](https://github.com/syl20bnr/spacemacs/pull/13860)
> 
> Probably should open an issue in Spacemacs together with a full stacktrace of the error

Thanks much, it helped!

**Comment by neverkas** [comment]
I've the same problem
